### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vatre** [shahineb/deep_deformable_registration#1]
# Preprocessing

- [ ] Scaling
- [ ] Reducing
- [ ] Unify different formats

# Architecture

- [x] Implement the voxelmorph
    - [x] Initial affine transformation to globally align the data
    - [x] CNN for the second transformation with more degrees of freedom
- [ ] read papers
- [ ] ???
- [ ] Profit
